shared:
    image: golang:1.13
    environment:
        GOPATH: /sd/workspace
        # hyperhq/hyperd is not using go module so turning off the module explicitly
        GO111MODULE: off

jobs:
    main:
        steps:
            # To verify if the hyperctl-build script works
            - hyperctl-build: bash -xe scripts/hyperctl-build.sh
            - chmod: chmod +x ./hyperctl
            - test-hyperctl: ./hyperctl info -h
        requires:
            - ~pr
            - ~commit
    publish:
        steps:
            - hyperctl-build: bash -xe scripts/hyperctl-build.sh
            - chmod: chmod +x ./hyperctl
            - test-hyperctl: ./hyperctl info -h
            # Dependencies for the scripts; should make the scripts share steps in the future
            - install-dependencies: |
                apt-get update
                apt-get install -y bzip2
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - tag: ./ci/git-tag.sh
            - release: ./ci/git-release.sh
        environment:
            RELEASE_FILE: hyperctl
        secrets:
            # Pushing tags to Git
            - GIT_KEY
            # Pushing releases to GitHub
            - GITHUB_TOKEN
        requires:
            - main
